# Generated by Django 4.0.1 on 2022-03-17 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_item_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leaders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('image', models.ImageField(max_length=30, upload_to='')),
                ('position', models.CharField(max_length=50)),
                ('facebook', models.CharField(max_length=50)),
                ('twitter', models.CharField(max_length=30)),
                ('instagram', models.CharField(max_length=50)),
                ('whatsapp', models.CharField(max_length=50)),
            ],
        ),
    ]
