# Generated by Django 4.0.1 on 2022-03-17 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_settlement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settlement',
            name='phone_number',
            field=models.FloatField(),
        ),
    ]
