# Generated by Django 4.0.1 on 2022-03-18 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_alter_settlement_phone_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Settlement',
        ),
    ]
