# Generated by Django 4.1.4 on 2024-08-15 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_delete_settlement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('region', models.CharField(max_length=20)),
                ('distric', models.CharField(max_length=20)),
                ('ward', models.CharField(max_length=20)),
                ('street', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='leaders',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
